service: authorization-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  
  stage: dev
  region: eu-west-1
  profile: nodejs-aws


plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

resources:
  Outputs:
    authArn:
      Value: !GetAtt BasicAuthorizerLambdaFunction.Arn

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer