service: import-service

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: eu-west-1
  profile: nodejs-aws

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::my-awesome-store-s3"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::my-awesome-store-s3/*"

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
        bucket: my-awesome-store-s3
        event: s3:ObjectCreated:*
        rules:
          - prefix: uploaded/
        existing: true



